version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run python 2.7 tests and send coverage report
          command: |
            sudo pip install tox
            tox -ecover-circleci